"""Add state field with default value to clients table

Revision ID: a191c54e9aba
Revises: 53b572292021
Create Date: 2025-03-11 22:59:01.075724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a191c54e9aba'
down_revision: Union[str, None] = '53b572292021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attorney_id', table_name='attorney')
    op.drop_table('attorney')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('resume', sa.VARCHAR(length=50), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_table('attorney',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attorney_id', 'attorney', ['id'], unique=False)
    # ### end Alembic commands ###
